module.exports.sudo = require('./commands/sudo.js')
module.exports.server_admin = require('./commands/server_admin.js')
module.exports.game = require('./commands/game.js')
module.exports.open = require('./commands/open.js')
module.exports.Command = require('./commands/Command.js')
